# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  training_data/ultrafeedback_dpo_bmc: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
dpo_bmc_delta: 2.0
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: mistral-7b-base-dpo-bmc
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/mistral-7b-base-dpo-bmc
run_name: mistral-7b-base-dpo-bmc
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
